"""empty message

Revision ID: caf173c5d5bd
Revises: 
Create Date: 2020-08-28 15:57:52.550146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf173c5d5bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('deliveries', sa.Column('day', sa.String(length=50), nullable=True))
    op.drop_column('deliveries', 'area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('area', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('deliveries', 'day')
    op.drop_column('deliveries', 'city')
    # ### end Alembic commands ###
